name: Test

on:
  pull_request:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    name: Node v${{ matrix.node_version }}
    strategy:
      matrix:
        node_version: [12, 14, 16]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        name: Install Node v${{ matrix.node_version }}
        with:
          node-version: ${{ matrix.node_version }}
      - name: Install
        uses: bahmutov/npm-install@v1
      - name: Test
        run: yarn test
